id: IA74009B8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T23:59:45+00:00'
last_modified: '2022-06-16T03:59:27.807479+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3PD246
  title: དམྱལ་ཟངས་ནང་ན་ཀུ་རེ་མེད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B2F2:
      image_group_id: I2PD18291
      title: Volume 1 of dmyal zangs nang na ku re med/
      total_pages: 298
      order: 1
      base_file: B2F2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
